import { GlobalStateMetaAddAccessOutputRequest, GlobalStateMetaAddAccessOutputResponse, GlobalStateMetaAddLinkOutputRequest, GlobalStateMetaAddLinkOutputResponse, GlobalStateMetaAddObjectMetaOutputRequest, GlobalStateMetaAddObjectMetaOutputResponse, GlobalStateMetaAddPathConfigOutputRequest, GlobalStateMetaAddPathConfigOutputResponse, GlobalStateMetaClearAccessOutputRequest, GlobalStateMetaClearAccessOutputResponse, GlobalStateMetaClearLinkOutputRequest, GlobalStateMetaClearLinkOutputResponse, GlobalStateMetaClearObjectMetaOutputRequest, GlobalStateMetaClearObjectMetaOutputResponse, GlobalStateMetaClearPathConfigOutputRequest, GlobalStateMetaClearPathConfigOutputResponse, GlobalStateMetaRemoveAccessOutputRequest, GlobalStateMetaRemoveAccessOutputResponse, GlobalStateMetaRemoveLinkOutputRequest, GlobalStateMetaRemoveLinkOutputResponse, GlobalStateMetaRemoveObjectMetaOutputRequest, GlobalStateMetaRemoveObjectMetaOutputResponse, GlobalStateMetaRemovePathConfigOutputRequest, GlobalStateMetaRemovePathConfigOutputResponse, MetaOutputRequestCommon } from "./output_request";

export type MetaRequestCommon = MetaOutputRequestCommon;

export type GlobalStateMetaAddAccessRequest = GlobalStateMetaAddAccessOutputRequest;
export type GlobalStateMetaAddAccessResponse =GlobalStateMetaAddAccessOutputResponse;

export type GlobalStateMetaRemoveAccessRequest = GlobalStateMetaRemoveAccessOutputRequest;
export type GlobalStateMetaRemoveAccessResponse = GlobalStateMetaRemoveAccessOutputResponse;

export type GlobalStateMetaClearAccessRequest = GlobalStateMetaClearAccessOutputRequest;
export type GlobalStateMetaClearAccessResponse = GlobalStateMetaClearAccessOutputResponse;

export type GlobalStateMetaAddLinkRequest = GlobalStateMetaAddLinkOutputRequest;
export type GlobalStateMetaAddLinkResponse = GlobalStateMetaAddLinkOutputResponse;

export type GlobalStateMetaRemoveLinkRequest = GlobalStateMetaRemoveLinkOutputRequest;
export type GlobalStateMetaRemoveLinkResponse = GlobalStateMetaRemoveLinkOutputResponse;

export type GlobalStateMetaClearLinkRequest = GlobalStateMetaClearLinkOutputRequest;
export type GlobalStateMetaClearLinkResponse = GlobalStateMetaClearLinkOutputResponse;

export type GlobalStateMetaAddObjectMetaRequest = GlobalStateMetaAddObjectMetaOutputRequest;
export type GlobalStateMetaAddObjectMetaResponse = GlobalStateMetaAddObjectMetaOutputResponse;

export type GlobalStateMetaRemoveObjectMetaRequest = GlobalStateMetaRemoveObjectMetaOutputRequest;
export type GlobalStateMetaRemoveObjectMetaResponse = GlobalStateMetaRemoveObjectMetaOutputResponse;

export type GlobalStateMetaClearObjectMetaRequest = GlobalStateMetaClearObjectMetaOutputRequest;
export type GlobalStateMetaClearObjectMetaResponse = GlobalStateMetaClearObjectMetaOutputResponse;

export type GlobalStateMetaAddPathConfigRequest = GlobalStateMetaAddPathConfigOutputRequest;
export type GlobalStateMetaAddPathConfigResponse = GlobalStateMetaAddPathConfigOutputResponse;

export type GlobalStateMetaRemovePathConfigRequest = GlobalStateMetaRemovePathConfigOutputRequest;
export type GlobalStateMetaRemovePathConfigResponse = GlobalStateMetaRemovePathConfigOutputResponse;

export type GlobalStateMetaClearPathConfigRequest = GlobalStateMetaClearPathConfigOutputRequest;
export type GlobalStateMetaClearPathConfigResponse = GlobalStateMetaClearPathConfigOutputResponse;
