import { GlobalStateMetaAddAccessOutputRequest, GlobalStateMetaAddAccessOutputResponse, GlobalStateMetaAddLinkOutputRequest, GlobalStateMetaAddLinkOutputResponse, GlobalStateMetaClearAccessOutputRequest, GlobalStateMetaClearAccessOutputResponse, GlobalStateMetaClearLinkOutputRequest, GlobalStateMetaClearLinkOutputResponse, GlobalStateMetaRemoveAccessOutputRequest, GlobalStateMetaRemoveAccessOutputResponse, GlobalStateMetaRemoveLinkOutputRequest, GlobalStateMetaRemoveLinkOutputResponse, MetaOutputRequestCommon } from "./output_request";

export type MetaRequestCommon = MetaOutputRequestCommon;

export type GlobalStateMetaAddAccessRequest = GlobalStateMetaAddAccessOutputRequest;
export type GlobalStateMetaAddAccessResponse =GlobalStateMetaAddAccessOutputResponse;

export type GlobalStateMetaRemoveAccessRequest = GlobalStateMetaRemoveAccessOutputRequest;
export type GlobalStateMetaRemoveAccessResponse = GlobalStateMetaRemoveAccessOutputResponse;

export type GlobalStateMetaClearAccessRequest = GlobalStateMetaClearAccessOutputRequest;
export type GlobalStateMetaClearAccessResponse = GlobalStateMetaClearAccessOutputResponse;

export type GlobalStateMetaAddLinkRequest = GlobalStateMetaAddLinkOutputRequest;
export type GlobalStateMetaAddLinkResponse = GlobalStateMetaAddLinkOutputResponse;

export type GlobalStateMetaRemoveLinkRequest = GlobalStateMetaRemoveLinkOutputRequest;
export type GlobalStateMetaRemoveLinkResponse = GlobalStateMetaRemoveLinkOutputResponse;

export type GlobalStateMetaClearLinkRequest = GlobalStateMetaClearLinkOutputRequest;
export type GlobalStateMetaClearLinkResponse = GlobalStateMetaClearLinkOutputResponse;