import { TransControlTaskGroupOutputRequest, TransControlTaskGroupOutputResponse, TransControlTaskOutputRequest, TransCreateTaskOutputRequest, TransCreateTaskOutputResponse, TransGetContextOutputRequest, TransGetContextOutputResponse, TransGetTaskGroupStateOutputRequest, TransGetTaskGroupStateOutputResponse, TransGetTaskStateOutputRequest, TransGetTaskStateOutputResponse, TransPublishFileOutputRequest, TransPublishFileOutputResponse, TransPutContextOutputRequest, TransQueryTasksOutputRequest } from './output_request';

export type TransGetContextRequest = TransGetContextOutputRequest;
export type TransGetContextResponse = TransGetContextOutputResponse;

export type TransPutContextRequest = TransPutContextOutputRequest;

export type TransCreateTaskRequest = TransCreateTaskOutputRequest;
export type TransCreateTaskResponse = TransCreateTaskOutputResponse;

export type TransControlTaskRequest = TransControlTaskOutputRequest;

export type TransGetTaskStateRequest = TransGetTaskStateOutputRequest;
export type TransGetTaskStateResponse = TransGetTaskStateOutputResponse;

export type TransQueryTasksRequest = TransQueryTasksOutputRequest;
export type TransQueryTasksResponse = TransQueryTasksOutputRequest;

export type TransPublishFileRequest = TransPublishFileOutputRequest;
export type TransPublishFileResponse = TransPublishFileOutputResponse;

export type TransGetTaskGroupStateRequest = TransGetTaskGroupStateOutputRequest;
export type TransGetTaskGroupStateResponse = TransGetTaskGroupStateOutputResponse;

export type TransControlTaskGroupRequest = TransControlTaskGroupOutputRequest;
export type TransControlTaskGroupResponse = TransControlTaskGroupOutputResponse;